spring:
  application:
    name: api-gateway

server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 1000

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
    defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    customer:
      path: /customer/**
      serviceId: customer
      stripPrefix: false
    order:
      path: /order/**
      serviceId: order
      stripPrefix: false
    product:
      path: /product/**
      serviceId: product
      stripPrefix: false